stages:
  - build
  - deploy

build_image:
  stage: build
  tags: 
    - career-site-x5-dev
  image: docker-registry.x5.ru/docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u Danii.Afanasev -p ${password} docker-careerx5-dev.x5.ru/artifactory/docker-careerx5-dev
    - docker build -t x5frontend .
    - docker tag x5frontend docker-careerx5-dev.x5.ru/artifactory/docker-careerx5-dev:frontend
    - docker push docker-careerx5-dev.x5.ru/artifactory/docker-careerx5-dev:frontend

deploy_helm:
  stage: deploy
  tags:
    - career-site-x5-dev
  image: 
    name: docker-registry.x5.ru/alpine/helm:3.7.2
    entrypoint: [""] 
  script:
    - echo "$KUBECONFIG_CONTENT" > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig
    - helm uninstall myfrontendchart --namespace career-site || true
    - helm upgrade --install myfrontendchart --namespace career-site myfrontendchart/
