services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: avto-rent-frontend:latest
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 5175
      NODE_ENV: production
    ports:
      - "127.0.0.1:5175:5175"
    restart: unless-stopped