apiVersion: apps/v1
kind: Deployment
metadata:
  name: x5frontend
  labels:
    app: x5frontend # Здесь должен быть ключ: значение
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: x5frontend # И здесь тоже должен быть ключ: значение
  template:
    metadata:
      labels:
        app: x5frontend # И здесь
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
