   replicaCount: 1
   name: frontend

   image:
     repository: docker-careerx5-dev.x5.ru/artifactory/docker-careerx5-dev
     pullPolicy: Always
     tag: "frontend"
     imagePullSecrets: regcred

   nameOverride: ""
   fullnameOverride: ""

   service:
     type: ClusterIP
     port: 80

   ingress:
     enabled: true
     className: ""
     annotations:
       kubernetes.io/ingress.class: nginx
     hosts:
       - host: dev.tech.career.x5.ru
         paths:
           - path: /
             pathType: ImplementationSpecific

   resources: {}
